export const TYPES = {
    ATUALIZAR_CONFIGURACOES: 'ATUALIZAR_CONFIGURACOES',
    ATUALIZAR_BREADCRUMB: 'ATUALIZAR_BREADCRUMB',
    LIMPAR_BREADCRUMB: 'LIMPAR_BREADCRUMB',
    ADD_LINK_BREADCRUMB: 'ADD_LINK_BREADCRUMB',
    ATUALIZAR_LOGIN_USUARIO: 'ATUALIZAR_LOGIN_USUARIO'
};
